package com.tajuli.digitorandroid.editor.model

/**
 * V24 preset metadata layered on top of the stable V22 render families.
 * Persisted as a string id in ClipTransition so old projects remain valid and unknown future ids
 * can safely fall back to the V22 style.
 */
internal object TransitionPresetV24 {
    const val PULL_IN = "pull_in"
    const val PULL_OUT = "pull_out"
    const val ZOOM_IN = "zoom_in"
    const val ZOOM_OUT = "zoom_out"
    const val ZOOM_LENS = "zoom_lens"
    const val CAMERA_ZOOM = "camera_zoom"
    const val SWIPE_LEFT = "swipe_left"
    const val SWIPE_RIGHT = "swipe_right"
    const val SWIPE_UP = "swipe_up"
    const val SWIPE_DOWN = "swipe_down"
    const val SLIDE_LEFT = "slide_left"
    const val SLIDE_RIGHT = "slide_right"
    const val SLIDE_UP = "slide_up"
    const val SLIDE_DOWN = "slide_down"
    const val SPIN = "spin"
    const val ROTATE = "rotate"
    const val BLUR = "blur"
    const val MOTION_BLUR = "motion_blur"
    const val VERTICAL_BLUR = "vertical_blur"
    const val HORIZONTAL_BLUR = "horizontal_blur"
    const val BLUR_ZOOM = "blur_zoom"
    const val FADE = "fade"
    const val FADE_IN = "fade_in"
    const val FADE_OUT = "fade_out"
    const val BLACK_FADE = "black_fade"
    const val WHITE_FADE = "white_fade"
    const val MIX = "mix"
    const val DISSOLVE = "dissolve"
    const val CROSS_FADE = "cross_fade"
    const val FLASH = "flash"
    const val WHITE_FLASH = "white_flash"
    const val CAMERA_FLASH = "camera_flash"
    const val FLICKER = "flicker"
    const val LIGHT_LEAK = "light_leak"
    const val LENS_FLARE = "lens_flare"
    const val FILM_BURN = "film_burn"
    const val GLITCH = "glitch"
    const val RGB_GLITCH = "rgb_glitch"
    const val DIGITAL_GLITCH = "digital_glitch"
    const val DISTORTION = "distortion"
    const val SHAKE = "shake"
    const val CAMERA_SHAKE = "camera_shake"
    const val STRETCH = "stretch"
    const val WARP = "warp"
    const val CUBE_3D = "cube_3d"
    const val PAGE_TURN = "page_turn"
    const val MASK_TRANSITION = "mask_transition"
    const val SPLIT = "split"
    const val VELOCITY = "velocity"
    const val BEAT_SYNC = "beat_sync"
}
