package com.tajuli.digitorandroid.editor.processing

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Color
import com.google.mediapipe.framework.image.BitmapImageBuilder
import com.google.mediapipe.framework.image.ByteBufferExtractor
import com.google.mediapipe.tasks.core.BaseOptions
import com.google.mediapipe.tasks.core.Delegate
import com.google.mediapipe.tasks.vision.core.RunningMode
import com.google.mediapipe.tasks.vision.imagesegmenter.ImageSegmenter
import com.tajuli.digitorandroid.editor.model.TimelineClip
import java.io.File
import java.security.MessageDigest
import java.util.concurrent.ConcurrentHashMap
import kotlin.math.abs
import kotlin.math.max

private const val HAIR_MODEL_ASSET_V29 = "hair_segmenter.tflite"
private const val HAIR_MASK_LONG_EDGE_V29 = 192

/** One cached semantic-hair mask generated by MediaPipe HairSegmenter. */
data class BeautyHairMaskFrameV29(
    val sourceTimeUs: Long,
    val file: File,
)

data class BeautyHairMaskTrackV29(
    val sourceUri: String,
    val frames: List<BeautyHairMaskFrameV29>,
) {
    fun nearest(sourceTimeUs: Long): BeautyHairMaskFrameV29? {
        if (frames.isEmpty()) return null
        var low = 0
        var high = frames.lastIndex
        while (low <= high) {
            val mid = (low + high) ushr 1
            val value = frames[mid].sourceTimeUs
            when {
                value < sourceTimeUs -> low = mid + 1
                value > sourceTimeUs -> high = mid - 1
                else -> return frames[mid]
            }
        }
        val right = frames.getOrNull(low)
        val left = frames.getOrNull(low - 1)
        return when {
            left == null -> right
            right == null -> left
            abs(sourceTimeUs - left.sourceTimeUs) <= abs(right.sourceTimeUs - sourceTimeUs) -> left
            else -> right
        }
    }
}

/**
 * Local semantic-hair mask cache. Masks are small PNGs keyed by source URI + sampled source time,
 * so video masks can follow head movement without inflating project JSON.
 */
object BeautyHairMaskStoreV29 {
    private val indexCache = ConcurrentHashMap<String, BeautyHairMaskTrackV29>()

    fun index(context: Context, clip: TimelineClip): BeautyHairMaskTrackV29 {
        val key = cacheKey(clip.uri)
        return indexCache[key] ?: loadIndex(context, clip.uri).also { indexCache[key] = it }
    }

    fun hasCoverage(context: Context, clip: TimelineClip): Boolean {
        val track = index(context, clip)
        if (track.frames.isEmpty()) return false
        if (clip.isImageV21) return track.frames.any { it.file.isFile }
        val first = track.frames.firstOrNull()?.sourceTimeUs ?: return false
        val last = track.frames.lastOrNull()?.sourceTimeUs ?: return false
        val requestedEnd = (clip.sourceOutUs - 1L).coerceAtLeast(clip.sourceInUs)
        return first <= clip.sourceInUs && last >= requestedEnd
    }

    fun save(context: Context, sourceUri: String, sourceTimeUs: Long, mask: Bitmap): File {
        val dir = sourceDir(context, sourceUri).apply { mkdirs() }
        val target = File(dir, "$sourceTimeUs.png")
        val temp = File(dir, "$sourceTimeUs.png.tmp")
        temp.outputStream().buffered().use { stream ->
            check(mask.compress(Bitmap.CompressFormat.PNG, 100, stream)) { "Could not encode hair segmentation mask" }
        }
        if (target.exists()) target.delete()
        check(temp.renameTo(target)) { "Could not install hair segmentation mask" }
        indexCache.remove(cacheKey(sourceUri))
        return target
    }

    private fun loadIndex(context: Context, sourceUri: String): BeautyHairMaskTrackV29 {
        val frames = sourceDir(context, sourceUri).listFiles().orEmpty()
            .asSequence()
            .filter { it.isFile && it.extension.equals("png", ignoreCase = true) }
            .mapNotNull { file -> file.nameWithoutExtension.toLongOrNull()?.let { BeautyHairMaskFrameV29(it, file) } }
            .sortedBy { it.sourceTimeUs }
            .toList()
        return BeautyHairMaskTrackV29(sourceUri, frames)
    }

    private fun sourceDir(context: Context, sourceUri: String): File =
        File(File(context.filesDir, "beauty_hair_masks_v29"), cacheKey(sourceUri))

    private fun cacheKey(sourceUri: String): String = MessageDigest.getInstance("SHA-256")
        .digest(sourceUri.toByteArray())
        .joinToString("") { byte -> "%02x".format(byte) }
        .take(32)
}

/**
 * Dedicated semantic hair segmenter using Google's MediaPipe HairSegmenter model (512x512).
 * Model output is binary: category 0 background, category 1 hair.
 */
class BeautyHairSegmenterV29(context: Context) : AutoCloseable {
    private val segmenter: ImageSegmenter

    init {
        val baseOptions = BaseOptions.builder()
            .setModelAssetPath(HAIR_MODEL_ASSET_V29)
            .setDelegate(Delegate.CPU)
            .build()
        val options = ImageSegmenter.ImageSegmenterOptions.builder()
            .setBaseOptions(baseOptions)
            .setRunningMode(RunningMode.IMAGE)
            .setOutputCategoryMask(true)
            .setOutputConfidenceMasks(false)
            .build()
        segmenter = ImageSegmenter.createFromOptions(context.applicationContext, options)
    }

    fun segmentAndStore(context: Context, clip: TimelineClip, bitmap: Bitmap, sourceTimeUs: Long): Boolean {
        val result = segmenter.segment(BitmapImageBuilder(bitmap).build())
        val mpMask = result.categoryMask().orElse(null) ?: return false
        val width = mpMask.width.coerceAtLeast(1)
        val height = mpMask.height.coerceAtLeast(1)
        val categories = ByteBufferExtractor.extract(mpMask)
        categories.rewind()
        if (categories.remaining() < width * height) return false

        val pixels = IntArray(width * height)
        for (index in pixels.indices) {
            val category = categories.get().toInt() and 0xFF
            val value = if (category == 1) 255 else 0
            pixels[index] = Color.argb(255, value, value, value)
        }
        val fullMask = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        fullMask.setPixels(pixels, 0, width, 0, 0, width, height)
        val longEdge = max(width, height)
        val storedMask = if (longEdge <= HAIR_MASK_LONG_EDGE_V29) {
            fullMask
        } else {
            val scale = HAIR_MASK_LONG_EDGE_V29.toFloat() / longEdge.toFloat()
            Bitmap.createScaledBitmap(
                fullMask,
                (width * scale).toInt().coerceAtLeast(1),
                (height * scale).toInt().coerceAtLeast(1),
                true,
            )
        }
        try {
            BeautyHairMaskStoreV29.save(context.applicationContext, clip.uri, sourceTimeUs, storedMask)
        } finally {
            if (storedMask !== fullMask) storedMask.recycle()
            fullMask.recycle()
        }
        return true
    }

    override fun close() {
        segmenter.close()
    }
}
