package com.tajuli.digitorandroid.editor.processing

import android.content.Context
import android.graphics.Bitmap
import android.graphics.Color
import com.google.mediapipe.framework.image.BitmapImageBuilder
import com.google.mediapipe.framework.image.ByteBufferExtractor
import com.google.mediapipe.tasks.core.BaseOptions
import com.google.mediapipe.tasks.core.Delegate
import com.google.mediapipe.tasks.vision.core.RunningMode
import com.google.mediapipe.tasks.vision.imagesegmenter.ImageSegmenter
import com.tajuli.digitorandroid.editor.model.TimelineClip
import java.io.File
import java.security.MessageDigest
import java.util.concurrent.ConcurrentHashMap
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.roundToInt

private const val HAIR_MODEL_ASSET_V29 = "hair_segmenter.tflite"
private const val HAIR_CLASS_V34 = 1
private const val HAIR_MASK_LONG_EDGE_V29 = 384

/** One cached semantic-hair confidence mask generated by MediaPipe HairSegmenter. */
data class BeautyHairMaskFrameV29(
    val sourceTimeUs: Long,
    val file: File,
)

data class BeautyHairMaskTrackV29(
    val sourceUri: String,
    val frames: List<BeautyHairMaskFrameV29>,
) {
    fun nearest(sourceTimeUs: Long): BeautyHairMaskFrameV29? {
        if (frames.isEmpty()) return null
        var low = 0
        var high = frames.lastIndex
        while (low <= high) {
            val mid = (low + high) ushr 1
            val value = frames[mid].sourceTimeUs
            when {
                value < sourceTimeUs -> low = mid + 1
                value > sourceTimeUs -> high = mid - 1
                else -> return frames[mid]
            }
        }
        val right = frames.getOrNull(low)
        val left = frames.getOrNull(low - 1)
        return when {
            left == null -> right
            right == null -> left
            abs(sourceTimeUs - left.sourceTimeUs) <= abs(right.sourceTimeUs - sourceTimeUs) -> left
            else -> right
        }
    }
}

/**
 * V34 hair cache stores a soft confidence matte rather than a hard category cutout. This preserves
 * fine hair/head-cover boundaries and gives the renderer enough alpha information to cross-fade
 * between semantic anchors without flashing binary edges.
 */
object BeautyHairMaskStoreV29 {
    private val indexCache = ConcurrentHashMap<String, BeautyHairMaskTrackV29>()

    fun index(context: Context, clip: TimelineClip): BeautyHairMaskTrackV29 {
        val key = cacheKey(clip.uri)
        return indexCache[key] ?: loadIndex(context, clip.uri).also { indexCache[key] = it }
    }

    fun hasCoverage(context: Context, clip: TimelineClip): Boolean {
        val track = index(context, clip)
        if (track.frames.isEmpty()) return false
        if (clip.isImageV21) return track.frames.any { it.file.isFile }
        val first = track.frames.firstOrNull()?.sourceTimeUs ?: return false
        val last = track.frames.lastOrNull()?.sourceTimeUs ?: return false
        val requestedEnd = (clip.sourceOutUs - 1L).coerceAtLeast(clip.sourceInUs)
        return first <= clip.sourceInUs && last >= requestedEnd
    }

    fun save(context: Context, sourceUri: String, sourceTimeUs: Long, mask: Bitmap): File {
        val dir = sourceDir(context, sourceUri).apply { mkdirs() }
        val target = File(dir, "$sourceTimeUs.png")
        val temp = File(dir, "$sourceTimeUs.png.tmp")
        temp.outputStream().buffered().use { stream ->
            check(mask.compress(Bitmap.CompressFormat.PNG, 100, stream)) { "Could not encode hair confidence mask" }
        }
        if (target.exists()) target.delete()
        check(temp.renameTo(target)) { "Could not install hair confidence mask" }
        indexCache.remove(cacheKey(sourceUri))
        return target
    }

    private fun loadIndex(context: Context, sourceUri: String): BeautyHairMaskTrackV29 {
        val frames = sourceDir(context, sourceUri).listFiles().orEmpty()
            .asSequence()
            .filter { it.isFile && it.extension.equals("png", ignoreCase = true) }
            .mapNotNull { file -> file.nameWithoutExtension.toLongOrNull()?.let { BeautyHairMaskFrameV29(it, file) } }
            .sortedBy { it.sourceTimeUs }
            .toList()
        return BeautyHairMaskTrackV29(sourceUri, frames)
    }

    private fun sourceDir(context: Context, sourceUri: String): File =
        File(File(context.filesDir, "beauty_hair_masks_v34_confidence_384"), cacheKey(sourceUri))

    private fun cacheKey(sourceUri: String): String = MessageDigest.getInstance("SHA-256")
        .digest(sourceUri.toByteArray())
        .joinToString("") { byte -> "%02x".format(byte) }
        .take(32)
}

/**
 * Dedicated semantic hair segmenter. Callers can opt into strict GPU execution. Pro Cutout V51
 * does so to avoid a silent MediaPipe CPU fallback in the analysis hot path, while older beauty
 * tools retain the compatibility fallback by using the default requireGpu=false.
 */
class BeautyHairSegmenterV29(
    context: Context,
    requireGpu: Boolean = false,
) : AutoCloseable {
    private val segmenter: ImageSegmenter
    val usingGpuDelegate: Boolean

    init {
        val app = context.applicationContext
        val gpu = runCatching { createSegmenter(app, Delegate.GPU) }
        if (gpu.isSuccess) {
            segmenter = gpu.getOrThrow()
            usingGpuDelegate = true
        } else if (requireGpu) {
            throw IllegalStateException(
                "MediaPipe GPU delegate is required for Pro Cutout; CPU fallback is disabled",
                gpu.exceptionOrNull(),
            )
        } else {
            segmenter = createSegmenter(app, Delegate.CPU)
            usingGpuDelegate = false
        }
    }

    /** Returns a soft grayscale hair-confidence bitmap owned by the caller. */
    fun segmentSoftMask(bitmap: Bitmap): Bitmap? {
        val result = segmenter.segment(BitmapImageBuilder(bitmap).build())
        val masks = result.confidenceMasks().orElse(emptyList())
        val mpMask = masks.getOrNull(HAIR_CLASS_V34) ?: return null
        val width = mpMask.width.coerceAtLeast(1)
        val height = mpMask.height.coerceAtLeast(1)
        val confidences = ByteBufferExtractor.extract(mpMask).asFloatBuffer()
        confidences.rewind()
        if (confidences.remaining() < width * height) return null

        val pixels = IntArray(width * height)
        for (index in pixels.indices) {
            val confidence = confidences.get().coerceIn(0f, 1f)
            val x = ((confidence - .04f) / .88f).coerceIn(0f, 1f)
            val smooth = x * x * (3f - 2f * x)
            val value = (smooth * 255f).roundToInt().coerceIn(0, 255)
            pixels[index] = Color.argb(255, value, value, value)
        }

        val fullMask = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        fullMask.setPixels(pixels, 0, width, 0, 0, width, height)
        val longEdge = max(width, height)
        if (longEdge <= HAIR_MASK_LONG_EDGE_V29) return fullMask
        val scale = HAIR_MASK_LONG_EDGE_V29.toFloat() / longEdge.toFloat()
        return Bitmap.createScaledBitmap(
            fullMask,
            (width * scale).toInt().coerceAtLeast(1),
            (height * scale).toInt().coerceAtLeast(1),
            true,
        ).also { fullMask.recycle() }
    }

    fun segmentAndStore(context: Context, clip: TimelineClip, bitmap: Bitmap, sourceTimeUs: Long): Boolean {
        val storedMask = segmentSoftMask(bitmap) ?: return false
        try {
            BeautyHairMaskStoreV29.save(context.applicationContext, clip.uri, sourceTimeUs, storedMask)
        } finally {
            storedMask.recycle()
        }
        return true
    }

    override fun close() {
        segmenter.close()
    }

    private companion object {
        fun createSegmenter(context: Context, delegate: Delegate): ImageSegmenter {
            val baseOptions = BaseOptions.builder()
                .setModelAssetPath(HAIR_MODEL_ASSET_V29)
                .setDelegate(delegate)
                .build()
            val options = ImageSegmenter.ImageSegmenterOptions.builder()
                .setBaseOptions(baseOptions)
                .setRunningMode(RunningMode.IMAGE)
                .setOutputCategoryMask(false)
                .setOutputConfidenceMasks(true)
                .build()
            return ImageSegmenter.createFromOptions(context, options)
        }
    }
}
