package com.tajuli.digitorandroid.editor.render

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.opengl.GLES20
import android.opengl.GLUtils
import androidx.media3.common.VideoFrameProcessingException
import androidx.media3.common.util.GlProgram
import androidx.media3.common.util.GlUtil
import androidx.media3.common.util.Size
import androidx.media3.common.util.UnstableApi
import androidx.media3.effect.BaseGlShaderProgram
import androidx.media3.effect.GlEffect
import androidx.media3.effect.GlShaderProgram
import com.tajuli.digitorandroid.editor.model.BodyEffectCatalogV102
import com.tajuli.digitorandroid.editor.model.BodyEffectVectorV102
import com.tajuli.digitorandroid.editor.model.NodeAnimationDomain
import com.tajuli.digitorandroid.editor.model.NodeKind
import com.tajuli.digitorandroid.editor.model.SpatialNodeGraphPlan
import com.tajuli.digitorandroid.editor.model.TimelineClip
import com.tajuli.digitorandroid.editor.model.resolveTimedBodyEffectsV102
import com.tajuli.digitorandroid.editor.model.visibleEffects
import com.tajuli.digitorandroid.editor.preview.PreviewProjectRegistry
import com.tajuli.digitorandroid.editor.processing.PersonCutoutMaskFrameV43
import com.tajuli.digitorandroid.editor.processing.PersonCutoutMaskStoreV43
import com.tajuli.digitorandroid.editor.processing.personCutoutMaxGapUsV47
import kotlin.math.abs

/**
 * V102 body-aware creator effect graph.
 *
 * The graph consumes the durable PP-MattingV2 + hair + spatial-flow matte generated by the existing
 * Pro Cutout analyzer, but it never changes frame alpha. The full scene therefore stays intact.
 *
 * A second graph is deliberate: V25 effects are whole-frame pixels while these operations need a
 * semantic person matte. Both still execute the same Resolve-style serial/parallel topology, use the
 * same V26 source-time bars, and are installed identically in preview and export.
 */
@UnstableApi
internal class BodyEffectGraphV102 private constructor(
    private val clip: TimelineClip,
    private val preview: Boolean,
) : GlEffect {
    override fun toGlShaderProgram(context: Context, useHdr: Boolean): GlShaderProgram =
        Program(context.applicationContext, clip, preview, useHdr)

    companion object {
        fun forClip(clip: TimelineClip, preview: Boolean): BodyEffectGraphV102? {
            val editable = clip.nodeGraph.nodes.filter { it.kind == NodeKind.SERIAL || it.kind == NodeKind.PARALLEL }
            if (editable.isEmpty()) return null

            // Realtime graphs remain resident so tapping a Body effect is visible immediately.
            if (preview) return BodyEffectGraphV102(clip, true)

            val hasBodyEffect = editable.any { node ->
                node.visibleEffects().any { BodyEffectCatalogV102.isBodyEffect(it.name) }
            }
            val hasAnimatedEffects = editable.any { node ->
                clip.nodeAnimations.hasAnimation(node.id, NodeAnimationDomain.EFFECTS)
            }
            return if (hasBodyEffect || hasAnimatedEffects) BodyEffectGraphV102(clip, false) else null
        }
    }

    private class Program(
        private val appContext: Context,
        private val snapshotClip: TimelineClip,
        private val preview: Boolean,
        useHdr: Boolean,
    ) : BaseGlShaderProgram(
        /* useHighPrecisionColorComponents = */ useHdr,
        /* texturePoolCapacity = */ 1,
    ) {
        private val plan = SpatialNodeGraphPlan.compile(snapshotClip.nodeGraph)
        private val nodeProgram: GlProgram
        private val mixProgram: GlProgram
        private val copyProgram: GlProgram
        private var scratchTextures = IntArray(0)
        private var scratchFbos = IntArray(0)
        private var inputWidth = 1
        private var inputHeight = 1

        private var maskTextureA = 0
        private var maskTextureB = 0
        private var loadedPathA: String? = null
        private var loadedPathB: String? = null

        init {
            try {
                nodeProgram = newProgram(NODE_FRAGMENT_SHADER)
                mixProgram = newProgram(MIX_FRAGMENT_SHADER)
                copyProgram = newProgram(COPY_FRAGMENT_SHADER)
                maskTextureA = createMaskTexture()
                maskTextureB = createMaskTexture()
            } catch (error: GlUtil.GlException) {
                throw VideoFrameProcessingException(error)
            }
        }

        override fun configure(inputWidth: Int, inputHeight: Int): Size {
            this.inputWidth = inputWidth.coerceAtLeast(1)
            this.inputHeight = inputHeight.coerceAtLeast(1)
            try {
                releaseScratch()
                val count = plan.maximumScratchPasses.coerceAtLeast(1)
                scratchTextures = IntArray(count)
                scratchFbos = IntArray(count)
                for (index in 0 until count) {
                    val texture = GlUtil.createTexture(
                        this.inputWidth,
                        this.inputHeight,
                        useHighPrecisionColorComponents,
                    )
                    scratchTextures[index] = texture
                    scratchFbos[index] = GlUtil.createFboForTexture(texture)
                }
            } catch (error: GlUtil.GlException) {
                throw VideoFrameProcessingException(error)
            }
            return Size(inputWidth, inputHeight)
        }

        override fun drawFrame(inputTexId: Int, presentationTimeUs: Long) {
            try {
                val outputFbo = IntArray(1)
                GLES20.glGetIntegerv(GLES20.GL_FRAMEBUFFER_BINDING, outputFbo, 0)
                val media3OutputFbo = outputFbo[0]

                val currentClip = if (preview) {
                    PreviewProjectRegistry.clip(snapshotClip.id) ?: snapshotClip
                } else {
                    snapshotClip
                }
                val sourceUs = ParityRenderContract.sourceTimeUs(currentClip, presentationTimeUs)
                val bracket = personBracket(currentClip, sourceUs)
                val hasMaskA = bindMask(maskTextureA, bracket.a?.file?.absolutePath, true)
                val hasMaskB = bindMask(maskTextureB, bracket.b?.file?.absolutePath, false)
                val hasBodyMatte = hasMaskA || hasMaskB

                val slotTextures = IntArray(plan.operations.size) { inputTexId }
                var scratchCursor = 0

                fun nextScratch(): Pair<Int, Int> {
                    if (scratchCursor !in scratchTextures.indices) {
                        throw VideoFrameProcessingException(
                            IllegalStateException(
                                "Body V102 scratch pool exhausted: " + scratchCursor + "/" + scratchTextures.size,
                            ),
                            presentationTimeUs,
                        )
                    }
                    return scratchTextures[scratchCursor] to scratchFbos[scratchCursor++]
                }

                plan.operations.forEach { operation ->
                    when (operation.node.kind) {
                        NodeKind.IMPORT -> slotTextures[operation.slot] = inputTexId

                        NodeKind.SERIAL, NodeKind.PARALLEL -> {
                            val input = textureForSlot(
                                slotTextures,
                                operation.inputSlot,
                                operation.slot,
                                inputTexId,
                            )
                            val currentNode = if (preview) {
                                currentClip.nodeGraph.nodes.firstOrNull { it.id == operation.node.id }
                                    ?: operation.node
                            } else {
                                operation.node
                            }
                            val evaluated = currentClip.nodeAnimations.evaluateNode(currentNode, sourceUs)
                            val animatedById = evaluated.visibleEffects().associateBy { it.id }
                            val effectsWithTiming = currentNode.visibleEffects().map { base ->
                                val animated = animatedById[base.id] ?: base
                                animated.copy(
                                    name = base.name,
                                    sourceStartUsV26 = base.sourceStartUsV26,
                                    sourceEndUsV26 = base.sourceEndUsV26,
                                )
                            }
                            val vector = resolveTimedBodyEffectsV102(effectsWithTiming, currentClip, sourceUs)
                            if (vector.isIdentity || !hasBodyMatte) {
                                slotTextures[operation.slot] = input
                            } else {
                                val (texture, fbo) = nextScratch()
                                focus(fbo)
                                renderNode(
                                    inputTexture = input,
                                    vector = vector,
                                    sourceUs = sourceUs,
                                    hasMaskA = hasMaskA,
                                    hasMaskB = hasMaskB,
                                    temporalMix = bracket.mix,
                                )
                                slotTextures[operation.slot] = texture
                            }
                        }

                        NodeKind.MIX -> {
                            val base = textureForSlot(
                                slotTextures,
                                operation.mixerBaseSlot,
                                operation.slot,
                                inputTexId,
                            )
                            var accumulator = base
                            operation.mixerInputSlots.forEach { branchSlot ->
                                if (branchSlot !in 0 until operation.slot) return@forEach
                                val branch = slotTextures[branchSlot]
                                if (branch == base) return@forEach
                                val (texture, fbo) = nextScratch()
                                focus(fbo)
                                renderMix(accumulator, branch, base)
                                accumulator = texture
                            }
                            slotTextures[operation.slot] = accumulator
                        }

                        NodeKind.OUTPUT -> {
                            slotTextures[operation.slot] = textureForSlot(
                                slotTextures,
                                operation.inputSlot,
                                operation.slot,
                                inputTexId,
                            )
                        }
                    }
                }

                val finalTexture = if (plan.outputSlot in slotTextures.indices) {
                    slotTextures[plan.outputSlot]
                } else {
                    inputTexId
                }
                GlUtil.focusFramebufferUsingCurrentContext(media3OutputFbo, inputWidth, inputHeight)
                renderCopy(finalTexture)
                GlUtil.checkGlError()
            } catch (error: VideoFrameProcessingException) {
                throw error
            } catch (error: GlUtil.GlException) {
                throw VideoFrameProcessingException(error, presentationTimeUs)
            }
        }

        private fun renderNode(
            inputTexture: Int,
            vector: BodyEffectVectorV102,
            sourceUs: Long,
            hasMaskA: Boolean,
            hasMaskB: Boolean,
            temporalMix: Float,
        ) {
            nodeProgram.use()
            nodeProgram.setSamplerTexIdUniform("uTexSampler", inputTexture, 0)
            nodeProgram.setSamplerTexIdUniform("uMaskA", maskTextureA, 1)
            nodeProgram.setSamplerTexIdUniform("uMaskB", maskTextureB, 2)
            nodeProgram.setFloatsUniform(
                "uTexelSize",
                floatArrayOf(1f / inputWidth.toFloat(), 1f / inputHeight.toFloat()),
            )
            nodeProgram.setFloatUniform("uHasMaskA", if (hasMaskA) 1f else 0f)
            nodeProgram.setFloatUniform("uHasMaskB", if (hasMaskB) 1f else 0f)
            nodeProgram.setFloatUniform("uTemporalMix", temporalMix)
            nodeProgram.setFloatUniform("uOutline", vector.outline)
            nodeProgram.setFloatUniform("uGlow", vector.glow)
            nodeProgram.setFloatUniform("uAura", vector.aura)
            nodeProgram.setFloatUniform("uRgbSplit", vector.rgbSplit)
            nodeProgram.setFloatUniform("uSilhouette", vector.silhouette)
            nodeProgram.setFloatUniform("uPulse", vector.pulse)
            nodeProgram.setFloatUniform("uTime", (sourceUs % 10_000_000L).toFloat() / 1_000_000f)
            nodeProgram.bindAttributesAndUniforms()
            GLES20.glDisable(GLES20.GL_BLEND)
            GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP, 0, 4)
        }

        private fun renderMix(accumulator: Int, branch: Int, base: Int) {
            mixProgram.use()
            mixProgram.setSamplerTexIdUniform("uAccumulator", accumulator, 0)
            mixProgram.setSamplerTexIdUniform("uBranch", branch, 1)
            mixProgram.setSamplerTexIdUniform("uBase", base, 2)
            mixProgram.bindAttributesAndUniforms()
            GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP, 0, 4)
        }

        private fun renderCopy(texture: Int) {
            copyProgram.use()
            copyProgram.setSamplerTexIdUniform("uTexSampler", texture, 0)
            copyProgram.bindAttributesAndUniforms()
            GLES20.glDisable(GLES20.GL_BLEND)
            GLES20.glDrawArrays(GLES20.GL_TRIANGLE_STRIP, 0, 4)
        }

        private fun textureForSlot(
            slots: IntArray,
            slot: Int,
            currentSlot: Int,
            sourceTexture: Int,
        ): Int = if (slot in 0 until currentSlot) slots[slot] else sourceTexture

        private fun focus(fbo: Int) {
            GlUtil.focusFramebufferUsingCurrentContext(fbo, inputWidth, inputHeight)
            GLES20.glDisable(GLES20.GL_BLEND)
        }

        private fun personBracket(clip: TimelineClip, sourceUs: Long): MaskBracket {
            val frames = PersonCutoutMaskStoreV43.index(appContext, clip).frames.filter { it.file.isFile }
            if (frames.isEmpty()) return MaskBracket.empty()

            val maxGapUs = personCutoutMaxGapUsV47(clip.resolvedCutoutV43().analysisQualityV47)
            if (frames.size == 1) {
                val frame = frames[0]
                return if (abs(sourceUs - frame.sourceTimeUs) <= maxGapUs) {
                    MaskBracket(frame, frame, 0f)
                } else {
                    MaskBracket.empty()
                }
            }

            var rightIndex = frames.binarySearchBy(sourceUs) { it.sourceTimeUs }
            if (rightIndex >= 0) return MaskBracket(frames[rightIndex], frames[rightIndex], 0f)
            rightIndex = -rightIndex - 1
            val right = frames.getOrNull(rightIndex)
            val left = frames.getOrNull(rightIndex - 1)

            if (left == null) {
                return right?.takeIf { abs(it.sourceTimeUs - sourceUs) <= maxGapUs }
                    ?.let { MaskBracket(it, it, 0f) }
                    ?: MaskBracket.empty()
            }
            if (right == null) {
                return left.takeIf { abs(sourceUs - it.sourceTimeUs) <= maxGapUs }
                    ?.let { MaskBracket(it, it, 0f) }
                    ?: MaskBracket.empty()
            }

            val leftDistance = abs(sourceUs - left.sourceTimeUs)
            val rightDistance = abs(right.sourceTimeUs - sourceUs)
            val span = (right.sourceTimeUs - left.sourceTimeUs).coerceAtLeast(1L)
            if (span > maxGapUs) {
                return when {
                    leftDistance <= rightDistance && leftDistance <= maxGapUs -> MaskBracket(left, left, 0f)
                    rightDistance <= maxGapUs -> MaskBracket(right, right, 0f)
                    else -> MaskBracket.empty()
                }
            }
            if (leftDistance > maxGapUs && rightDistance > maxGapUs) return MaskBracket.empty()

            val mix = ((sourceUs - left.sourceTimeUs).toDouble() / span.toDouble())
                .toFloat()
                .coerceIn(0f, 1f)
            return MaskBracket(left, right, mix)
        }

        private fun bindMask(texture: Int, path: String?, slotA: Boolean): Boolean {
            val loaded = if (slotA) loadedPathA else loadedPathB
            if (path == null) {
                if (loaded != null) {
                    uploadMaskBitmap(texture, null)
                    if (slotA) loadedPathA = null else loadedPathB = null
                }
                return false
            }
            if (loaded == path) return true
            val bitmap = BitmapFactory.decodeFile(path) ?: return false
            try {
                uploadMaskBitmap(texture, bitmap)
                if (slotA) loadedPathA = path else loadedPathB = path
            } finally {
                bitmap.recycle()
            }
            return true
        }

        private fun createMaskTexture(): Int {
            val ids = IntArray(1)
            GLES20.glGenTextures(1, ids, 0)
            val texture = ids[0]
            GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, texture)
            GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_MIN_FILTER, GLES20.GL_LINEAR)
            GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_MAG_FILTER, GLES20.GL_LINEAR)
            GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_WRAP_S, GLES20.GL_CLAMP_TO_EDGE)
            GLES20.glTexParameteri(GLES20.GL_TEXTURE_2D, GLES20.GL_TEXTURE_WRAP_T, GLES20.GL_CLAMP_TO_EDGE)
            uploadMaskBitmap(texture, null)
            return texture
        }

        private fun uploadMaskBitmap(texture: Int, bitmap: Bitmap?) {
            GLES20.glBindTexture(GLES20.GL_TEXTURE_2D, texture)
            if (bitmap != null) {
                GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, bitmap, 0)
            } else {
                val black = Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888)
                try {
                    black.eraseColor(android.graphics.Color.BLACK)
                    GLUtils.texImage2D(GLES20.GL_TEXTURE_2D, 0, black, 0)
                } finally {
                    black.recycle()
                }
            }
        }

        private fun newProgram(fragmentShader: String): GlProgram =
            GlProgram(VERTEX_SHADER, fragmentShader).also { program ->
                program.setBufferAttribute(
                    "aFramePosition",
                    GlUtil.getNormalizedCoordinateBounds(),
                    GlUtil.HOMOGENEOUS_COORDINATE_VECTOR_SIZE,
                )
            }

        private fun releaseScratch() {
            scratchFbos.forEach { if (it != 0) GlUtil.deleteFbo(it) }
            scratchTextures.forEach { if (it != 0) GlUtil.deleteTexture(it) }
            scratchFbos = IntArray(0)
            scratchTextures = IntArray(0)
        }

        override fun release() {
            super.release()
            try {
                releaseScratch()
                listOf(maskTextureA, maskTextureB).filter { it != 0 }.forEach { texture ->
                    GLES20.glDeleteTextures(1, intArrayOf(texture), 0)
                }
                maskTextureA = 0
                maskTextureB = 0
                nodeProgram.delete()
                mixProgram.delete()
                copyProgram.delete()
            } catch (error: GlUtil.GlException) {
                throw VideoFrameProcessingException(error)
            }
        }

        private data class MaskBracket(
            val a: PersonCutoutMaskFrameV43?,
            val b: PersonCutoutMaskFrameV43?,
            val mix: Float,
        ) {
            companion object {
                fun empty() = MaskBracket(null, null, 0f)
            }
        }

        private companion object {
            const val VERTEX_SHADER = """
                attribute vec4 aFramePosition;
                varying vec2 vTexCoord;
                void main() {
                    gl_Position = aFramePosition;
                    vTexCoord = aFramePosition.xy * 0.5 + 0.5;
                }
            """

            const val COPY_FRAGMENT_SHADER = """
                precision highp float;
                uniform sampler2D uTexSampler;
                varying vec2 vTexCoord;
                void main() {
                    gl_FragColor = texture2D(uTexSampler, vTexCoord);
                }
            """

            const val MIX_FRAGMENT_SHADER = """
                precision highp float;
                uniform sampler2D uAccumulator;
                uniform sampler2D uBranch;
                uniform sampler2D uBase;
                varying vec2 vTexCoord;
                void main() {
                    vec4 accumulator = texture2D(uAccumulator, vTexCoord);
                    vec4 branch = texture2D(uBranch, vTexCoord);
                    vec4 base = texture2D(uBase, vTexCoord);
                    vec3 rgb = clamp(accumulator.rgb + branch.rgb - base.rgb, 0.0, 1.0);
                    gl_FragColor = vec4(rgb, accumulator.a);
                }
            """

            const val NODE_FRAGMENT_SHADER = """
                precision highp float;
                uniform sampler2D uTexSampler;
                uniform sampler2D uMaskA;
                uniform sampler2D uMaskB;
                uniform vec2 uTexelSize;
                uniform float uHasMaskA;
                uniform float uHasMaskB;
                uniform float uTemporalMix;
                uniform float uOutline;
                uniform float uGlow;
                uniform float uAura;
                uniform float uRgbSplit;
                uniform float uSilhouette;
                uniform float uPulse;
                uniform float uTime;
                varying vec2 vTexCoord;

                vec2 maskUv(vec2 videoUv) {
                    return vec2(videoUv.x, 1.0 - videoUv.y);
                }

                float bodyAt(vec2 uv) {
                    if (uHasMaskA < 0.5 && uHasMaskB < 0.5) return 0.0;
                    vec2 m = maskUv(clamp(uv, vec2(0.0), vec2(1.0)));
                    float a = uHasMaskA > 0.5 ? texture2D(uMaskA, m).r : 0.0;
                    float b = uHasMaskB > 0.5 ? texture2D(uMaskB, m).r : a;
                    if (uHasMaskA < 0.5) a = b;
                    return clamp(mix(a, b, clamp(uTemporalMix, 0.0, 1.0)), 0.0, 1.0);
                }

                float maxRing(vec2 uv, float radius) {
                    vec2 d = uTexelSize * radius;
                    float m = bodyAt(uv);
                    m = max(m, bodyAt(uv + vec2(d.x, 0.0)));
                    m = max(m, bodyAt(uv - vec2(d.x, 0.0)));
                    m = max(m, bodyAt(uv + vec2(0.0, d.y)));
                    m = max(m, bodyAt(uv - vec2(0.0, d.y)));
                    m = max(m, bodyAt(uv + d));
                    m = max(m, bodyAt(uv - d));
                    m = max(m, bodyAt(uv + vec2(d.x, -d.y)));
                    m = max(m, bodyAt(uv + vec2(-d.x, d.y)));
                    return m;
                }

                float minRing(vec2 uv, float radius) {
                    vec2 d = uTexelSize * radius;
                    float m = bodyAt(uv);
                    m = min(m, bodyAt(uv + vec2(d.x, 0.0)));
                    m = min(m, bodyAt(uv - vec2(d.x, 0.0)));
                    m = min(m, bodyAt(uv + vec2(0.0, d.y)));
                    m = min(m, bodyAt(uv - vec2(0.0, d.y)));
                    m = min(m, bodyAt(uv + d));
                    m = min(m, bodyAt(uv - d));
                    m = min(m, bodyAt(uv + vec2(d.x, -d.y)));
                    m = min(m, bodyAt(uv + vec2(-d.x, d.y)));
                    return m;
                }

                void main() {
                    vec4 source = texture2D(uTexSampler, vTexCoord);
                    if (uHasMaskA < 0.5 && uHasMaskB < 0.5) {
                        gl_FragColor = source;
                        return;
                    }

                    float rawBody = bodyAt(vTexCoord);
                    float body = smoothstep(0.04, 0.96, rawBody);
                    float nearBody = maxRing(vTexCoord, 2.2);
                    float farBody = maxRing(vTexCoord, 8.0);
                    float inside = minRing(vTexCoord, 1.7);
                    float boundary = clamp(nearBody - inside, 0.0, 1.0);
                    float outerGlow = clamp(nearBody - body, 0.0, 1.0);
                    float auraRing = clamp(farBody - nearBody, 0.0, 1.0);

                    float pulseWave = 0.72 + 0.28 * (0.5 + 0.5 * sin(uTime * 9.42477796));
                    float pulse = mix(1.0, pulseWave, clamp(uPulse, 0.0, 1.0));
                    float sweep = 0.5 + 0.5 * sin(vTexCoord.y * 7.0 + vTexCoord.x * 3.0 + uTime * 1.8);
                    vec3 cyan = vec3(0.03, 0.92, 1.00);
                    vec3 magenta = vec3(1.00, 0.08, 0.72);
                    vec3 neon = mix(cyan, magenta, sweep);

                    vec3 rgb = source.rgb;

                    if (uRgbSplit > 0.001 && body > 0.001) {
                        float px = 1.5 + 6.0 * clamp(uRgbSplit, 0.0, 1.5);
                        vec2 shift = vec2(uTexelSize.x * px, 0.0);
                        vec3 shifted = vec3(
                            texture2D(uTexSampler, clamp(vTexCoord + shift, vec2(0.0), vec2(1.0))).r,
                            source.g,
                            texture2D(uTexSampler, clamp(vTexCoord - shift, vec2(0.0), vec2(1.0))).b
                        );
                        rgb = mix(rgb, shifted, clamp(uRgbSplit * body * 0.88, 0.0, 1.0));
                    }

                    if (uSilhouette > 0.001 && body > 0.001) {
                        float luma = dot(source.rgb, vec3(0.2126, 0.7152, 0.0722));
                        vec3 stylized = neon * (0.20 + 0.36 * luma);
                        rgb = mix(rgb, stylized, clamp(uSilhouette * body * 0.94, 0.0, 1.0));
                    }

                    float outlineWeight = boundary * clamp(uOutline, 0.0, 1.5) * pulse;
                    rgb = mix(rgb, neon, clamp(outlineWeight, 0.0, 0.96));

                    float glowWeight = outerGlow * clamp(uGlow, 0.0, 1.5) * 0.72 * pulse;
                    float auraWeight = auraRing * clamp(uAura, 0.0, 1.5) * 0.52 * pulse;
                    rgb += neon * (glowWeight + auraWeight);

                    // A subtle inner response avoids a detached sticker look while keeping skin/clothes.
                    rgb += neon * body * clamp(uGlow, 0.0, 1.5) * 0.035 * pulse;
                    gl_FragColor = vec4(clamp(rgb, 0.0, 1.0), source.a);
                }
            """
        }
    }
}
